### ISSUE TITLE
pool timed out while waiting for an open connection during Tenant creation

### ISSUE THREAD

**Issue by Sshovon** [openwallet-foundation/agent-framework-javascript#1681]
I've created a multi-tenant solution where PostgreSQL, version 14.10, serves as the database. The module setup for Askar and tenants is outlined as follows:
```
askar: new AskarModule({
      ariesAskar,
      multiWalletDatabaseScheme: AskarMultiWalletDatabaseScheme.ProfilePerWallet,
    }),
 tenants: new TenantsModule(),
```
During a single agent session, I can create precisely 8 tenants. However, after re-initializing the agent, I regain the ability to create another set of 8 tenants. 
The logger trace indicates the following error for 9th tenant and subsequent ones.
```
DEBUG: Creating tenant with label core-tenant
DEBUG: Getting tenant agent for tenant '6f2d8b96-aede-430a-94c2-6ec3fe28a105'
DEBUG: Getting context for session with tenant '6f2d8b96-aede-430a-94c2-6ec3fe28a105'
DEBUG: Acquiring tenant session
DEBUG: Increasing current session count to 1 (max: 100)
DEBUG: Acquired tenant session (1 / 100)
DEBUG: Created tenant agent context for tenant '6f2d8b96-aede-430a-94c2-6ec3fe28a105'
DEBUG: Acquired lock for tenant '6f2d8b96-aede-430a-94c2-6ec3fe28a105' to get context
DEBUG: No agent context has been initialized for tenant '6f2d8b96-aede-430a-94c2-6ec3fe28a105', creating one
INFO: Initializing wallet 'tenant-6f2d8b96-aede-430a-94c2-6ec3fe28a105' {
  "storage": {
    "type": "postgres",
    "config": {
      "host": "localhost:5432",
      "connectTimeout": 10
    },
    "credentials": "[*****]"
  },
  "id": "tenant-6f2d8b96-aede-430a-94c2-6ec3fe28a105",
  "key": "[*****]",
  "keyDerivationMethod": "RAW"
}
DEBUG: Opening wallet for profile 'tenant-6f2d8b96-aede-430a-94c2-6ec3fe28a105'
ERROR: Error opening wallet for profile 'tenant-6f2d8b96-aede-430a-94c2-6ec3fe28a105' {
  "error": {
    "name": "Error",
    "stack": "Error: Backend error\nCaused by: pool timed out while waiting for an open connection\n    at cb (/home/frcs/nordivo/hovi/hovi-afj-agents/agents/node_modules/@hyperledger/aries-askar-nodejs/src/NodeJSAriesAskar.ts:167:25)\n    at Object.<anonymous> (/home/frcs/nordivo/hovi/hovi-afj-agents/agents/node_modules/ffi-napi/lib/callback.js:66:27)",
    "message": "Backend error\nCaused by: pool timed out while waiting for an open connection",
    "code": 1
  },
  "errorMessage": "Backend error\nCaused by: pool timed out while waiting for an open connection"
}
DEBUG: Releasing session because an error occurred while getting the context for tenant 6f2d8b96-aede-430a-94c2-6ec3fe28a105 {
  "errorMessage": "Error opening wallet for profile 'tenant-6f2d8b96-aede-430a-94c2-6ec3fe28a105'"
}

```
Now, If I use following wallet scheme I can create as many tenants as I want in a single agent session. 
```
askar: new AskarModule({
      ariesAskar,
      multiWalletDatabaseScheme: AskarMultiWalletDatabaseScheme.DatabasePerWallet
    }),
```
Following is my package.json info.
```
"dependencies": {
    "@aries-framework/anoncreds": "0.4.2",
    "@aries-framework/anoncreds-rs": "0.4.2",
    "@aries-framework/askar": "0.4.2",
    "@aries-framework/cheqd": "0.4.2",
    "@aries-framework/core": "0.4.2",
    "@aries-framework/indy-sdk": "0.4.2",
    "@aries-framework/indy-vdr": "0.4.2",
    "@aries-framework/node": "0.4.2",
    "@aries-framework/tenants": "0.4.2",
    "@hyperledger/anoncreds-nodejs": "^0.1.0",
    "@hyperledger/aries-askar-nodejs": "^0.1.0",
    "@hyperledger/indy-vdr-nodejs": "^0.1.0",
    "dotenv": "^16.3.1"
  },
  "devDependencies": {
    "ts-node": "^10.4.0",
    "typescript": "^5.2.2",
    "prettier": "^3.1.1"
  },
  "resolutions": {
    "@types/node": "^16.11.7",
    "ref-napi": "npm:@2060.io/ref-napi"
  }
```

**Comment by Sshovon** [comment]
This latest `@hyperledger/aries-askar-nodejs": "0.2.0-dev.5` package resolves the issue.
